apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflows-deployment
spec:
  selector:
    matchLabels:
      app: workflows-service
  template:
    metadata:
      annotations:  
        dapr.io/app-id: workflows
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
      labels:
        app: workflows
        app.kubernetes.io/name: workflows-service
        app.kubernetes.io/part-of: workflows-service
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: workflows
        image: salaboy/dapr-workflows:1.0.5-amd64
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=75 -XX:TieredStopAtLevel=1"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workflows
spec:
  selector:
    app: workflows-service
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080